"""initial_schema

Revision ID: d1c202db9b27
Revises:     
Create Date: 2026-05-29 19:58:42.705349+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic
revision: str = 'd1c202db9b27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('llm_fallback_1', sa.String(), nullable=True),
    sa.Column('llm_fallback_2', sa.String(), nullable=True),
    sa.Column('calendar_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('agent_email', sa.String(), nullable=True),
    sa.Column('agent_whatsapp', sa.String(), nullable=True),
    sa.Column('whatsapp_phone_id', sa.String(), nullable=True),
    sa.Column('qualification_threshold', sa.Integer(), nullable=False),
    sa.Column('session_ttl_minutes', sa.Integer(), nullable=False),
    sa.Column('visit_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('allowed_origins', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("plan IN ('basic', 'standard', 'pro')", name='ck_tenant_plan'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ingestion_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_checksum', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('valid_rows', sa.Integer(), nullable=True),
    sa.Column('inserted_rows', sa.Integer(), nullable=True),
    sa.Column('updated_rows', sa.Integer(), nullable=True),
    sa.Column('skipped_rows', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'success', 'partial', 'failed')", name='ck_ingestion_log_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('property_hash', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_bs', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_zone', sa.String(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parking_spots', sa.Integer(), nullable=True),
    sa.Column('vista_al_mar', sa.Boolean(), nullable=False),
    sa.Column('frente_playa', sa.Boolean(), nullable=False),
    sa.Column('uso_vacacional', sa.Boolean(), nullable=False),
    sa.Column('tipo_especial', sa.String(), nullable=True),
    sa.Column('capacidad_huespedes', sa.Integer(), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('description_es', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('raw_embed_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("property_type IN ('venta', 'arriendo', 'vacacional', 'local', 'posada', 'hotel', 'planos', 'terreno')", name='ck_property_type'),
    sa.CheckConstraint("status IN ('disponible', 'reservada', 'vendida')", name='ck_property_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_properties_external_id', 'properties', ['tenant_id', 'external_id'], unique=False)
    op.create_index('idx_properties_hash', 'properties', ['tenant_id', 'property_hash'], unique=False)
    op.create_index('idx_properties_tenant_status', 'properties', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_properties_tenant_type', 'properties', ['tenant_id', 'property_type'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('qualification_score', sa.Integer(), nullable=False),
    sa.Column('is_booking_active', sa.Boolean(), nullable=False),
    sa.Column('booking_step', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_active_at', sa.String(), nullable=False),
    sa.CheckConstraint("booking_step IN ('name', 'email', 'phone', 'date', 'time', 'notes', 'confirm') OR booking_step IS NULL", name='ck_session_booking_step'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_tenant_active', 'sessions', ['tenant_id', 'last_active_at'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('preferred_date', sa.String(), nullable=False),
    sa.Column('preferred_time', sa.String(), nullable=False),
    sa.Column('visit_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('qualification_score', sa.Integer(), nullable=True),
    sa.Column('is_international', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('calendar_event_id', sa.String(), nullable=True),
    sa.Column('whatsapp_sent', sa.Integer(), nullable=False),
    sa.Column('email_sent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('pendiente', 'confirmado', 'cancelado')", name='ck_lead_status'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_tenant_date', 'leads', ['tenant_id', 'created_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_message_role'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session', 'messages', ['session_id'], unique=False)
    op.create_index('idx_messages_tenant_date', 'messages', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_tenant_date', table_name='messages')
    op.drop_index('idx_messages_session', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_leads_tenant_date', table_name='leads')
    op.drop_table('leads')
    op.drop_index('idx_sessions_tenant_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_properties_tenant_type', table_name='properties')
    op.drop_index('idx_properties_tenant_status', table_name='properties')
    op.drop_index('idx_properties_hash', table_name='properties')
    op.drop_index('idx_properties_external_id', table_name='properties')
    op.drop_table('properties')
    op.drop_table('ingestion_logs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
