"""add_embedding_column

Revision ID: da871408ec95
Revises:     d1c202db9b27
Create Date: 2026-06-03 17:56:56.069018+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic
revision: str = 'da871408ec95'
down_revision: Union[str, None] = 'd1c202db9b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector requiere la extensión 'vector' antes de usar el tipo Vector.
    # En Neon/PostgreSQL hay que crearla explícitamente; en SQLite se omite.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('properties', sa.Column('embedding', Vector(384), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'embedding')
    # ### end Alembic commands ###
